### ISSUE TITLE
Add link to Apiary

### ISSUE THREAD

**Issue by rubickcz** [mall-pay-developers/selfcare-API#19]
Could you please add link to Apiary to repo description for convenience? Thanks.

**Comment by czabaj** [comment]
Odkaz na APIary máš v levém panelu pod odkazem na "Fork...", pozor, ten odkaz na "Fork..." skutečně udělá co píše, je potřeba kliknout na to pod tím...

![Screenshot 2020-05-06 at 10 10 50](https://user-images.githubusercontent.com/47554112/81152384-3111ec00-8f82-11ea-81db-771172b184df.png)

**Comment by rubickcz** [comment]
I think you misunderstood me, I would like to have link **to** Apiary here, in the repo description/readme.
