### ISSUE TITLE
Replace AccountUpgradeApplicationRequest to object

### ISSUE THREAD

**Issue by MPdevelopers** [mall-pay-developers/selfcare-API#28]
Replace
` + Attributes (AccountUpgradeApplicationRequest)`
To
` + Attributes (object)`

In examples of revolving loan form.

**Comment by MPdevelopers** [comment]
https://github.com/mall-pay-developers/selfcare-API/pull/22/files#r313876814

**Comment by cedel1** [comment]
No, to je takové nešikovné - objevuje se tu taková tendence, že z objektů, které lze dědit v jednotlivých requestech/dalších objektech přecházíme na zápis konkrétních objektů/atributů/requestů a responses v ne jednotlivých místech - což dost ztíží údržbu. Jakákoli změna se pak bude muset udělat na X místech, místo na jednom v tom objektu.

**Comment by MPdevelopers** [comment]
Souhlas. Zavírám.
