### ISSUE TITLE
AccountUpgradeApplicationRequest by neměl mít required fieldy

### ISSUE THREAD

**Issue by vaclavnovotny** [mall-pay-developers/selfcare-API#55]
Na AccountUpgradeApplicationRequest je jako required uvedený field `bankBusinessCardReturnUrl` ale je nesmysl abychom ho tam _pokaždé_ posílali.

https://github.com/mall-pay-developers/selfcare-API/blob/master/apiary.apib#L2066

Dále jsou v AccountUpgradeApplicationResponse uvedené `isCourierFinished` a `isContractActive `, tam už to není takový fail, ale vzheldem k tomu, že v JS je `false` ekvivalentní s `undefined`, je to `required` naprosto zbytečné a komplikuje nám to mock server.

https://github.com/mall-pay-developers/selfcare-API/blob/master/apiary.apib#L2104

**Comment by zzuzzy** [comment]
Ad1. Ano, dává smysl udělat `bankBusinessCardReturnUrl` nepovinné.
Ad2. Jde sice o definici odpovědi z BE na FE, ale můžeme to také znepovinit. Udělám PR.

**Comment by vaclavnovotny** [comment]
Již fixnuto
